[window]
opacity = 1
padding = { x = 18, y = 18 }
decorations = "none"

[font]
size = 11.0

[font.normal]
family = "GohuFont 11 Nerd Font"
style = "Regular"

[colors.primary]
background = "#0F0900"
foreground = "#ffb000"

[colors.cursor]
text = "#1a1000"
cursor = "#ffb000"

[colors.normal]
black   = "#1a1000"
red     = "#cc7000"
green   = "#ffb000"
yellow  = "#ffc933"
blue    = "#b37700"
magenta = "#cc7000"
cyan    = "#ffb000"
white   = "#ffcc66"

[colors.bright]
black   = "#4d3800"
red     = "#ff8c00"
green   = "#ffc933"
yellow  = "#ffdb70"
blue    = "#e6a100"
magenta = "#ff8c00"
cyan    = "#ffcc66"
white   = "#ffe6a3"

[colors.selection]
text = "#1a1000"
background = "#ffb000"

[scrolling]
history = 5000

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal]
osc52 = "CopyPaste"
