FROM archlinux:latest

RUN pacman -Syu --needed --noconfirm \
    base bash-completion bat bc diffutils eza fzf git git-delta \
    glibc-locales inetutils less lsof man-db man-pages neovim openssh \
    pigz pkgconf rsync sudo time tree unzip vte-common wget wl-clipboard \
    words xorg-xauth yazi zip zoxide \
    ddrescue testdisk scanmem hexedit perl-image-exiftool gdb

CMD ["/bin/bash"]
