FROM archlinux:latest

RUN pacman -Syu --needed --noconfirm \
    base bash-completion bat bc diffutils eza fzf git git-delta \
    glibc-locales inetutils less lsof man-db man-pages neovim openssh \
    pigz pkgconf rsync sudo time tree unzip vte-common wget wl-clipboard \
    words xorg-xauth yazi zip zoxide \
    nmap gobuster whois mtr traceroute tcpdump socat bind nss-mdns \
    android-tools scrcpy

CMD ["/bin/bash"]
