set show_hidden true
set preview_images true
set confirm_on_delete multiple
set update_title true
set wrap_scroll true
set save_console_history true
mime ^application/pdf, has xdg-open, X, flag f = xdg-open -- "$@"
mime ^text, label editor = "$EDITOR" -- "$@"
ext html|htm, has firefox, X, flag f = firefox -- "$@"
mime ^image, has feh, X, flag f = feh -- "$@"
mime ^video|^audio, has mpv, X, flag f = mpv -- "$@"
